# podvm_payload image from where we get kata binaries artifacts, e.g. pause-bundle, kata-agent and guest components
# https://github.com/openshift/cloud-api-adaptor/tree/osc-release
# Must be RHEL 9.6 based
PODVM_PAYLOAD_IMAGE=quay.io/redhat-user-workloads/ose-osc-tenant/osc-podvm-payload@sha256:fec2a53170336125bcd5b8f11c3420871cf9f2a117b679a62aadf3292335c9a8
# Base image used to build the NVIDIA drivers
# Must be RHEL 9.6 based
#NVIDIA_DRIVERS_BASE_IMAGE=registry.access.redhat.com/ubi10:10.1-1772441712
NVIDIA_DRIVERS_BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.6
# NVIDIA Driver Version
NVIDIA_DRIVERS_VERSION=580.105.08
# kernel-core package version to be installed in the $(uname -r) format
# Must be RHEL 9.6 based
KERNEL_UNAME=5.14.0-570.62.1.el9_6.s390x
# List of runtime classes we want to pre-build an initrd. Don't use quotation marks
# "kata-osbuilder.sh -h" shows the list of runtime classes supported
PRE_BUILD_INITRDS=kata-cc
# Artifactory authentication token for downloading packages
# Set this to your Artifactory API token or leave empty if not needed
ARTIFACTORY_TOKEN=
